const initialProducts = [
  {
    name: 'Neem Coated Urea (46% N)',
    category: 'Nitrogen',
    price: 899,
    unit: '50 kg Bag',
    description: 'High-purity urea with neem coating to slow nitrogen release and prevent leaching. Ensures vibrant lush green growth.',
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&auto=format&fit=crop&q=80',
    stock: 75,
    rating: 4.8,
    npk: '46-0-0',
    composition: 'Total Nitrogen 46% min, Neem Oil Coating 0.05%',
    suitableCrops: ['Paddy', 'Wheat', 'Maize', 'Sugarcane', 'Vegetables'],
    manufacturer: 'National Fertilizer Corp',
    featured: true,
  },
  {
    name: 'DAP - Diammonium Phosphate (18:46:0)',
    category: 'Phosphate',
    price: 1350,
    unit: '50 kg Bag',
    description: 'Premium granulated phosphorus fertilizer providing essential phosphate for vigorous root establishment and early vegetative vigor.',
    image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&auto=format&fit=crop&q=80',
    stock: 50,
    rating: 4.7,
    npk: '18-46-0',
    composition: 'Nitrogen 18%, Available Phosphate 46%',
    suitableCrops: ['Cotton', 'Pulses', 'Oilseeds', 'Potato', 'Wheat'],
    manufacturer: 'IFFCO Agro Tech',
    featured: true,
  },
  {
    name: 'Balanced NPK 19-19-19 Foliar Special',
    category: 'Complex',
    price: 1150,
    unit: '25 kg Bag',
    description: '100% water-soluble complex fertilizer with equal proportions of nitrogen, phosphorus, and potassium for all plant stages.',
    image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=600&auto=format&fit=crop&q=80',
    stock: 45,
    rating: 4.9,
    npk: '19-19-19',
    composition: 'Total N 19%, P2O5 19%, K2O 19%',
    suitableCrops: ['Tomato', 'Chilli', 'Fruit Orchards', 'Flowers', 'Paddy'],
    manufacturer: 'Mahadhan Agri',
    featured: true,
  },
  {
    name: 'Enriched Vermicompost & Humic Organic Mix',
    category: 'Organic',
    price: 549,
    unit: '40 kg Bag',
    description: '100% natural organic compost enriched with beneficial earthworms, humic acids, and seaweed extract. Improves soil biology.',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&auto=format&fit=crop&q=80',
    stock: 80,
    rating: 4.9,
    npk: 'Organic Bio-Matrix',
    composition: 'Organic Matter 35%, Humic Acid 6%, Beneficial Microbes',
    suitableCrops: ['All Fruits', 'Vegetables', 'Organic Farming', 'Spices'],
    manufacturer: 'GreenEarth Bio Organics',
    featured: true,
  },
  {
    name: 'MOP - Muriate of Potash (60% K2O)',
    category: 'Potassium',
    price: 920,
    unit: '50 kg Bag',
    description: 'Essential potassium fertilizer for drought tolerance, pest resistance, grain filling, and fruit sweetness.',
    image: 'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?w=600&auto=format&fit=crop&q=80',
    stock: 40,
    rating: 4.5,
    npk: '0-0-60',
    composition: 'Potassium Chloride 60% K2O equivalent',
    suitableCrops: ['Banana', 'Sugarcane', 'Potato', 'Groundnut', 'Paddy'],
    manufacturer: 'Coromandel International',
    featured: false,
  },
  {
    name: 'Chelated Micronutrient Fertilizer Mix',
    category: 'Micronutrients',
    price: 680,
    unit: '5 kg Bucket',
    description: 'Multi-micronutrient cocktail containing Zinc, Iron, Manganese, Boron, Copper, and Molybdenum in EDTA chelated form.',
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80',
    stock: 65,
    rating: 4.8,
    npk: 'Micronutrient Complex',
    composition: 'Zn 3.0%, Fe 2.0%, Mn 1.0%, B 0.5%, Cu 0.5%, Mo 0.05%',
    suitableCrops: ['Citrus', 'Pomegranate', 'Vegetables', 'Grapes', 'Paddy'],
    manufacturer: 'Aries Agro Limited',
    featured: false,
  },
  {
    name: 'Calcium Nitrate with Boron (Liquid/Granular)',
    category: 'Nitrogen',
    price: 1280,
    unit: '25 kg Bag',
    description: 'Prevents fruit blossom-end rot, strengthens cell walls, improves shelf-life and crispness of harvested produce.',
    image: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=600&auto=format&fit=crop&q=80',
    stock: 35,
    rating: 4.6,
    npk: '15.5-0-0 + 18.8% Ca + 0.3% B',
    composition: 'Nitrate Nitrogen 14.4%, Ammoniacal N 1.1%, Ca 18.8%, Boron 0.3%',
    suitableCrops: ['Tomato', 'Capsicum', 'Apple', 'Watermelon', 'Strawberry'],
    manufacturer: 'Yara Agri Solutions',
    featured: false,
  },
  {
    name: 'Rhizobium & PSB Bio-Fertilizer Culture',
    category: 'Bio-Fertilizer',
    price: 399,
    unit: '2 Litre Can',
    description: 'Consortium of nitrogen-fixing bacteria and phosphate-solubilizing bacteria (PSB) that unlocks fixed soil nutrients naturally.',
    image: 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?w=600&auto=format&fit=crop&q=80',
    stock: 90,
    rating: 4.7,
    npk: 'Bacterial Inoculant',
    composition: 'Viable bacterial count > 1x10^8 CFU/ml',
    suitableCrops: ['Pulses', 'Soybean', 'Groundnut', 'Gram', 'Lentils'],
    manufacturer: 'BioTech Crop Care',
    featured: false,
  },
  {
    name: 'Zinc Sulphate Heptahydrate (21% Zn)',
    category: 'Micronutrients',
    price: 490,
    unit: '10 kg Pack',
    description: 'Critical zinc supplement for correcting Khaira disease in rice and chlorosis in maize and horticultural crops.',
    image: 'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?w=600&auto=format&fit=crop&q=80',
    stock: 55,
    rating: 4.5,
    npk: '21% Zinc + 10% Sulphur',
    composition: 'Zinc (as Zn) 21% min, Sulphur (as S) 10%',
    suitableCrops: ['Rice / Paddy', 'Maize', 'Wheat', 'Onion', 'Garlic'],
    manufacturer: 'AgroGrow Minerals',
    featured: false,
  },
  {
    name: 'SOP - Potassium Sulphate 0-0-50 + 17.5% S',
    category: 'Potassium',
    price: 1450,
    unit: '25 kg Bag',
    description: 'Chloride-free premium potassium and sulphur fertilizer for chloride-sensitive crops like tobacco, grapes, and potato.',
    image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?w=600&auto=format&fit=crop&q=80',
    stock: 30,
    rating: 4.9,
    npk: '0-0-50 + 17.5% S',
    composition: 'Potassium (as K2O) 50%, Sulphur (as S) 17.5%',
    suitableCrops: ['Tobacco', 'Grapes', 'Potato', 'Tea', 'Coffee'],
    manufacturer: 'SQM Specialties',
    featured: true,
  },
];

module.exports = initialProducts;
